channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.4
  - pip
  - cmake
  - ninja
  - libstdcxx-ng
  - scikit-build-core
  - pip:
      #- torch==2.2.2+cu121 --extra-index-url https://download.pytorch.org/whl/cu121
      #- torchvision==0.17.2+cu121 --extra-index-url https://download.pytorch.org/whl/cu121
      #- torchaudio==2.2.2+cu121 --extra-index-url https://download.pytorch.org/whl/cu121

      - chromadb==0.4.24
      - ctransformers==0.2.27
      - faiss-cpu==1.8.0
      - langchain==0.1.16
      - langchain-openai==0.1.3
      - pikepdf==8.15.0
      - pillow_heif==0.16.0
      - PyMuPDF==1.23.26
      - python-box==7.1.1
      - rank-bm25==0.2.2
      - sentence-transformers==2.6.0
      - simsimd==3.3.0
      - streamlit==1.33.0
      - transformers>=4.38.0
      - accelerate
      - bitsandbytes
      - umap-learn==0.5.5
      - unstructured==0.13.2
      - unstructured-inference==0.7.27
      - pdf2image==1.17.0
      - pdfminer.six==20231228
      - opencv-python==4.9.0.80
      - soundfile==0.12.1
      - mutagen==1.47.0
      - pygame-ce==2.4.1
      - pygame==2.5.2
      - SpeechRecognition==3.10.3
      - pyttsx3==2.90
      - pyaudio==0.2.14
      - sounddevice==0.4.6
      - faster-whisper
      - TTS==0.22.0
      - numpy
      - scipy
      - librosa
      - fsspec
      - numba
      - torchinfo
      - multiprocess
      - auto-gptq

